[package]
name = "parser"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = "0.19.6"
phf = { version = "0.10.0", features = ["macros"] }
common = { path = "../common" }

[build-dependencies]
lalrpop = "0.19.6"

